{% set name = "mo-future" %}
{% set version = "3.1.19316" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 0a6e00f132721bb385e1d109e0b9ffa589699f6589d1367eb0b26e9f1b09ebc7

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - mo_future

about:
  home: "https://github.com/klahnakoski/mo-files"
  license: MPL-2.0
  license_family: "MOZILLA"
  license_file: "LICENSE"
  summary: "More future! Make Python 2/3 compatibility a bit easier"

extra:
  recipe-maintainers:
    - xhochy
