{% set name = "mo-future" %}
{% set version = "6.265.22338" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 80e2d814e9c911364a08c5c5009eff7febff8e9f18e70f6a7113a7b9c42de9cd

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7

test:
  imports:
    - mo_future
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/klahnakoski/mo-files
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: More future! Make Python 2/3 compatibility a bit easier

extra:
  recipe-maintainers:
    - xhochy
