travis:
  secure:
    BINSTAR_TOKEN: KmaKvOc5OD3b+v1g14/h6H1QQuOU9pmwPFGjiaYb+I7g9D562RSwemjxjQ51jUUCZVRQI6YqDsEoDBckQh9ZsfjBvr2G3TnEa33k+Uuzz2QfMZAzRrh6+xDorZh0aiBySkw31u6rI4A3Bg30DwGE4FGceb8ib5ggrLL4+gPXBJ0PMPatm064f3TqnFRK9Dj/+x/5VomKkQAzCSHZBGZxyl6HbMEaysgX/bZrxJnyN6iM/kalkl6YSbr9ABc3sWHGgjBxL0Ed+kQupbxIb6Mw5HSCnnkBqo5jDMvi2+VkbnWOCVjbQ7S1bLGxobseV8sSGQkkhm95ENPX0h48T76C3g0RfxZkYsNTlRuOHUHHYqeCQxfH01pZ/54AsfN+VZqgn1Z2S0CZpS6/mlLePjOrt0LwEHsBmJzUgywME5+qSSZz+7pEKprJbPVTfJD4AIBjI/vBG2q4yqqy7FlbShYBQMG6rgyKG/OqqtTON93e+LOb9aQZSrOIfgfAH/hDnxMbivTOnB1RhpGqr2oZpCt6n5j+bR5tJw6am5OJc/HYxy+BZDRTxCo9F4iYAYAP+R5v9MK3MQ0mDjstrjXP0WvmU7rcOFFp1vMbuLReEi8mrmHETyyv5O0giPh2yPQDWBFlpdIk9bpdowgJVUHKvEUBx8whNOeQKCCNvUssjQjQAys=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
